TestConfig:
  Name: ratis-test
  Experiments: 1
  Iterations: 1
  WaitDuration: 30
  StartupDuration: 1 # seconds
SchedulerConfig:
  Type: QL
  Steps: 50
  ClientRequests: 2
  Seed: 42
  Params:
    client_request_probability: 0.01
    Epsilon: 0.1
    Gamma: 0.7
    Alpha: 0.3
NetworkConfig:
  BaseReplicaPort: 6000
  BaseInterceptorPort: 10000
  Protocol: "http"
  MessageType: GRPC
FaultConfig:
  Faults:
    - Type: dummy # does nothing
      Params: {}
    - Type: restart
      Params:
        node: 0
    - Type: restart
      Params:
        node: 1
    - Type: crash
      Params:
        node: 0
ProcessConfig:
  NumReplicas: 3
  Timeout: 10
  OutputDir: output
  ReplicaScript: scripts/ratis_server.sh
  ClientScripts:
    - scripts/ratis_client_0.sh
    # - scripts/ratis_client_1.sh
    # - scripts/ratis_client_2.sh
    # - scripts/ratis_client_3.sh
  CleanScript: scripts/ratis_clean.sh
  ReplicaParams:
    - "6000 10001 10002 n0"
    - "10003 6001 10005 n1"
    - "10006 10007 6002 n2"
    # - "6000 10001 10002 n0"
    # - "10003 6001 10005 n1"
    # - "10006 10007 6002 n2"
