TestConfig:
  Name: ratis-test
  Experiments: 1
  Iterations: 10
  WaitDuration: 50 # Time duration to wait between execution steps in milliseconds
SchedulerConfig: #TODO - Seperate the scheduler param
  Type: "random"
  Steps: 100
  Seed: 42
  Params: {}
NetworkConfig:
  BaseReplicaPort: 6000
  BaseInterceptorPort: 10000
  Protocol: "http2c"
FaultConfig:
  Faults:
    - Type: "Dummy"
      Params:
        name: "Jimmy"
        age: 42
    - Type: "Dummy"
      Params:
        name: "Alberto"
        age: 33
#    - Type: "Partition"
#      Params: # these are mostly for testing, to see if the marshaller works
#        StartQuantity: 1
#        StartUnit: "Messages" # or "Seconds"
#        DurationQuantity: 3
#        DurationUnit: "Messages" # or "Seconds"
#        Nodes: [["n0", "n1"], ["n2", "n3"]]
ProcessConfig:
  NumReplicas: 3
  Timeout: 10
  OutputDir: output
  ReplicaScript: scripts/ratis_server.sh
  ClientScripts: [ client.sh ]
  CleanScript: scripts/ratis_clean.sh
  ReplicaParams:
    # - "6000 6001 6002 n0"
    # - "6000 6001 6002 n1"
    # - "6000 6001 6002 n2"
    - "6000 10001 10002 n0"
    - "10000 6001 10002 n1"
    - "10000 10001 6002 n2"
