TestConfig:
  Name: ratis-test
  Experiments: 1
  Iterations: 1
  WaitDuration: 1
  StartupDuration: 0 # seconds
SchedulerConfig:
  Type: "random"
  Steps: 100
  ClientRequests: 2
  Seed: 42
  Params: {"client_request_probability": 0.01}
NetworkConfig:
  BaseReplicaPort: 6000
  BaseInterceptorPort: 10000
  MessageType: GRPC
FaultConfig:
  Faults:
    - Type: dummy # does nothing
      Params: {}
    - Type: dummy
      Params: {}
    - Type: restart
      Params:
        node: 0
    - Type: restart
      Params:
        node: 1
    - Type: crash
      Params:
        node: 0
#    - Type: "Partition"
#      Params: # these are mostly for testing, to see if the marshaller works
#        StartQuantity: 1
#        StartUnit: "Messages" # or "Seconds"
#        DurationQuantity: 3
#        DurationUnit: "Messages" # or "Seconds"
#        Nodes: [["n0", "n1"], ["n2", "n3"]]
ProcessConfig:
  NumReplicas: 3
  Timeout: 60
  OutputDir: output
  ReplicaScript: scripts/ratis_server.sh
  ClientScripts:
    - scripts/ratis_client_0.sh
    # - scripts/ratis_client_1.sh
    # - scripts/ratis_client_2.sh
    # - scripts/ratis_client_3.sh
  CleanScript: scripts/ratis_clean.sh
  ReplicaParams:
    - "6000 10001 10002 n0"
    - "10003 6001 10005 n1"
    - "10006 10007 6002 n2"
    # - "6000 10001 10002 n0"
    # - "10003 6001 10005 n1"
    # - "10006 10007 6002 n2"
