TestConfig:
  Name: ratis-test
  Experiments: 10
  Iterations: 10000
SchedulerConfig: #TODO - Seperate the scheduler param
  Type: random
  Steps: 100
  Seed: 42
  Params: {} 
NetworkConfig:
  BaseReplicaPort: 6000
  BaseInterceptorPort: 10000
ProcessConfig:
  NumReplicas: 3
  Timeout: 10
  OutputDir: /Users/berkay/Documents/Research/dstest/output
  ReplicaScript: /Users/berkay/Documents/Research/dstest/scripts/ratis_server.sh
  ClientScripts: [ client.sh ]
  CleanScript: /Users/berkay/Documents/Research/dstest/scripts/ratis_clean.sh
  ReplicaParams: 
    - "n0"
    - "n1"
    - "n2"